### ISSUE TITLE
Should protobufs ignore default values for optional fields?

### ISSUE THREAD

**Issue by relwell** [lookout/protobuffy#18]
For optional protobuf definitions with default fields, exporting that protobuf to JSON does not include the default value for that field. Is this the desired behavior?

**Comment by relwell** [comment]
Does anyone have an opinion on this? @avalade maybe?

**Comment by avalade** [comment]
In looking at https://developers.google.com/protocol-buffers/docs/proto3#default, it appears that this is the desired behavior, specifically the sentence:

> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire. 

So it seems when marshalling into an object, an optional field that has a default should be initialized with the default.  However, when serializing it, the value should NOT be written out to the stream.  So in this case, JSON should not contain the default value for the field if we follow what Google's document says.

With that being said, is it safe for us to assert that any consumer of the JSON would have the IDL file to know that there's a default value specified for the field?

**Comment by relwell** [comment]
Not presently -- but I think in the future. Happy to close this one.
